# NXC Command

# Constants for use with the NXC ArrayOp function and the NBC arrop statement. 
"oparr_sum"    	= "OPARR_SUM"    
"oparr_mean"   	= "OPARR_MEAN"   
"oparr_sumsqr" 	= "OPARR_SUMSQR" 
"oparr_std"    	= "OPARR_STD"    
"oparr_min"    	= "OPARR_MIN"    
"oparr_max"    	= "OPARR_MAX"    
"oparr_sort"   	= "OPARR_SORT"   
"oparr_toupper"	= "OPARR_TOUPPER"
"oparr_tolower"	= "OPARR_TOLOWER"

# Constant offsets into the Command module IOMAP structure. 
"offset_format_string"  	= "CommandOffsetFormatString"   
"offset_prc_handler"    	= "CommandOffsetPRCHandler"     
"offset_tick"          	    = "CommandOffsetTick"           
"offset_offset_ds"      	= "CommandOffsetOffsetDS"       
"offset_offset_dva"     	= "CommandOffsetOffsetDVA"      
"offset_prog_status"    	= "CommandOffsetProgStatus"     
"offset_awake"         	    = "CommandOffsetAwake"          
"offset_activate_flag"  	= "CommandOffsetActivateFlag"   
"offset_deactivate_flag"	= "CommandOffsetDeactivateFlag" 
"offset_file_name"      	= "CommandOffsetFileName"       
"offset_memory_pool"    	= "CommandOffsetMemoryPool"     
"offset_sync_time"      	= "CommandOffsetSyncTime"       
"offset_sync_tick"      	= "CommandOffsetSyncTick"          

# Constants defining communication error conditions. 
"err_comm_chan_not_ready"	= "ERR_COMM_CHAN_NOT_READY"   
"err_comm_chan_invalid"  	= "ERR_COMM_CHAN_INVALID"     
"err_comm_buffer_full"   	= "ERR_COMM_BUFFER_FULL"      
"err_comm_bus_err"       	= "ERR_COMM_BUS_ERR"         

# Constants defining various fatal error conditions. 
"err_arg"            		= "ERR_ARG"                
"err_instr"          		= "ERR_INSTR"              
"err_file"           		= "ERR_FILE"               
"err_ver"            		= "ERR_VER"                
"err_mem"            		= "ERR_MEM"                
"err_bad_ptr"        		= "ERR_BAD_PTR"            
"err_clump_count"    		= "ERR_CLUMP_COUNT"        
"err_no_code"        		= "ERR_NO_CODE"                 
"err_insane_offset"  		= "ERR_INSANE_OFFSET"      
"err_bad_pool_size"  		= "ERR_BAD_POOL_SIZE"      
"err_loader_err"     		= "ERR_LOADER_ERR"         
"err_spotcheck_fail" 		= "ERR_SPOTCHECK_FAIL"     
"err_no_active_clump"		= "ERR_NO_ACTIVE_CLUMP"    
"err_default_offsets"		= "ERR_DEFAULT_OFFSETS"    
"err_memmgr_fail"    		= "ERR_MEMMGR_FAIL"        
"err_non_fatal"      		= "ERR_NON_FATAL"          

# Constants defining general error conditions. 
"err_invalid_port" 	= "ERR_INVALID_PORT" 
"err_invalid_field"	= "ERR_INVALID_FIELD"
"err_invalid_queue"	= "ERR_INVALID_QUEUE"
"err_invalid_size" 	= "ERR_INVALID_SIZE" 
"err_no_prog"      	= "ERR_NO_PROG"      

# Constants defining various states of the command module virtual machine. 
"prog_idle"   	= "PROG_IDLE"   
"prog_ok"     	= "PROG_OK"     
"prog_running"	= "PROG_RUNNING"
"prog_error"  	= "PROG_ERROR"  
"prog_abort"  	= "PROG_ABORT"  
"prog_reset"  	= "PROG_RESET"  

# Constants defining errors that can occur during remote control (RC) direct command operations. 
"err_rc_illegal_val"	= "ERR_RC_ILLEGAL_VAL"
"err_rc_bad_packet" 	= "ERR_RC_BAD_PACKET" 
"err_rc_unknown_cmd"	= "ERR_RC_UNKNOWN_CMD"
"err_rc_failed"     	= "ERR_RC_FAILED"     

# Constants for use in the sys_call() function or NBC syscall statement. 
"file_open_read"          	    = "FileOpenRead"                                   
"file_open_write"         	    = "FileOpenWrite"                                   
"file_open_append"        	    = "FileOpenAppend"                                   
"file_read"              	    = "FileRead"                                   
"file_write"             	    = "FileWrite"                                   
"file_close"             	    = "FileClose"                                   
"file_resolve_handle"     	    = "FileResolveHandle"                                   
"file_rename"            	    = "FileRename"                                   
"file_delete"            	    = "FileDelete"                                   
"sound_play_tone"         	    = "SoundPlayTone"                                   
"sound_play_file"         	    = "SoundPlayFile"                                   
"sound_set_state"         	    = "SoundSetState"                                   
"sound_get_state"         	    = "SoundGetState"                                   
"draw_point"             	    = "DrawPoint"                                   
"draw_text"              	    = "DrawText"                                   
"draw_circle"            	    = "DrawCircle"                                   
"draw_line"              	    = "DrawLine"                                   
"draw_graphic"           	    = "DrawGraphic"                                   
"draw_rect"              	    = "DrawRect"                                   
"read_button"            	    = "ReadButton"                                   
"set_screen_mode"         	    = "SetScreenMode"                                   
"comm_ls_read"            	    = "CommLSRead"                                   
"comm_ls_write"           	    = "CommLSWrite"                                   
"random_number"          	    = "RandomNumber"                                   
"comm_ls_check_status"     	    = "CommLSCheckStatus"                                   
"message_write"          	    = "MessageWrite"                                   
"get_start_tick"          	    = "GetStartTick"                                   
"comm_bt_check_status"     	    = "CommBTCheckStatus"                                   
"message_read"           	    = "MessageRead"                                   
"comm_bt_read"            	    = "CommBTRead"                                   
"comm_bt_write"           	    = "CommBTWrite"                                   
"io_map_read"             	    = "IOMapRead"                                   
"keep_alive"             	    = "KeepAlive"                                   
"color_sensor_read"       	    = "ColorSensorRead"                                   
"io_map_write"            	    = "IOMapWrite"                                   
"comm_bt_connection"      	    = "CommBTConnection"                                   
"comm_bt_on_off"           	    = "CommBTOnOff"                                   
"comm_hs_read"            	    = "CommHSRead"                                   
"comm_hs_write"           	    = "CommHSWrite"                                   
"read_sem_data"           	    = "ReadSemData"                                   
"comm_hs_check_status"     	    = "CommHSCheckStatus"                                   
"compute_calib_value"     	    = "ComputeCalibValue"                                   
"write_sem_data"          	    = "WriteSemData"                                   
"datalog_write"          	    = "DatalogWrite"                                   
"update_calib_cache_info"  	    = "UpdateCalibCacheInfo"                                   
"set_sleep_timeout_val"    	    = "SetSleepTimeoutVal"                                   
"datalog_get_times"       	    = "DatalogGetTimes"                                   
"input_pin_function"      	    = "InputPinFunction"                                   
"list_files"             	    = "ListFiles"                                   
"io_map_write_by_id"            = "IOMapWriteByID"                                   
"io_map_read_by_id"             = "IOMapReadByID"                                   
"comm_execute_function"   	    = "CommExecuteFunction"                                   
"display_execute_function"	    = "DisplayExecuteFunction"                                   
"file_find_first"         	    = "FileFindFirst"                                   
"loader_execute_function" 	    = "LoaderExecuteFunction"                                   
"file_open_write_linear"   	    = "FileOpenWriteLinear"                                   
"file_find_next"          	    = "FileFindNext"                                   
"file_open_read_linear"    	    = "FileOpenReadLinear"                                   
"file_open_write_non_linear"    = "FileOpenWriteNonLinear"                                   
"comm_ls_write_ex"         	    = "CommLSWriteEx"                                   
"comm_hs_control"         	    = "CommHSControl"                                   
"file_resize"            	    = "FileResize"                                   
"file_seek"              	    = "FileSeek"                                   
"draw_polygon"           	    = "DrawPolygon"                                   
"draw_graphic_array"      	    = "DrawGraphicArray"                                   
"draw_font"              	    = "DrawFont"                                   
"draw_ellipse"           	    = "DrawEllipse"                                   
"read_last_response"      	    = "ReadLastResponse"                                   
"memory_manager"         	    = "MemoryManager"                                   
"random_ex"              	    = "RandomEx"          
"file_tell"            	  	    = "FileTell"                                   

# Constants for use with the sleep() function. 
"ms_1"  		= "MS_1"                                      
"ms_2"  		= "MS_2"   
"ms_3"  		= "MS_3"   
"ms_4"  		= "MS_4"   
"ms_5"  		= "MS_5"   
"ms_6"  		= "MS_6"   
"ms_7"  		= "MS_7"   
"ms_8"  		= "MS_8"   
"ms_9"  		= "MS_9"   
"ms_10" 		= "MS_10"  
"ms_20" 		= "MS_20"  
"ms_30" 		= "MS_30"  
"ms_40" 		= "MS_40"  
"ms_50" 		= "MS_50"  
"ms_60" 		= "MS_60"  
"ms_70" 		= "MS_70"  
"ms_80" 		= "MS_80"  
"ms_90" 		= "MS_90"  
"ms_100"		= "MS_100" 
"ms_150"		= "MS_150" 
"ms_200"		= "MS_200" 
"ms_250"		= "MS_250" 
"ms_300"		= "MS_300" 
"ms_350"		= "MS_350" 
"ms_400"		= "MS_400" 
"ms_450"		= "MS_450" 
"ms_500"		= "MS_500" 
"ms_600"		= "MS_600" 
"ms_700"		= "MS_700" 
"ms_800"		= "MS_800" 
"ms_900"		= "MS_900" 
"sec_1" 		= "SEC_1"  
"sec_2" 		= "SEC_2"  
"sec_3" 		= "SEC_3"  
"sec_4" 		= "SEC_4"  
"sec_5" 		= "SEC_5"  
"sec_6" 		= "SEC_6"  
"sec_7" 		= "SEC_7"  
"sec_8" 		= "SEC_8"  
"sec_9" 		= "SEC_9"  
"sec_10"		= "SEC_10" 
"sec_15"		= "SEC_15" 
"sec_20"		= "SEC_20" 
"sec_30"		= "SEC_30" 
"min_1" 		= "MIN_1"  
"note_whole"  	= "NOTE_WHOLE"  
"note_half"   	= "NOTE_HALF"      
"note_quarter"	= "NOTE_QUARTER"   
"note_eight"  	= "NOTE_EIGHT"     
"note_sixteen"	= "NOTE_SIXTEEN"   

# Constants defining possible VM states. 
"times_up"     	= "TIMES_UP"       
"rotate_queue" 	= "ROTATE_QUEUE"   
"stop_req"     	= "STOP_REQ"       
"breakout_req" 	= "BREAKOUT_REQ"   
"clump_suspend"	= "CLUMP_SUSPEND"  
"clump_done"   	= "CLUMP_DONE"     

# 
"stat_msg_empty_mailbox"	= "STAT_MSG_EMPTY_MAILBOX"
"stat_comm_pending"     	= "STAT_COMM_PENDING"     
"pool_max_size"         	= "POOL_MAX_SIZE"         
"no_err"                	= "NO_ERR"                

# Functions for accessing and modifying Command module features. 
"current_tick("            		= "CurrentTick("
"first_tick("              		= "FirstTick("
"reset_sleep_timer("        	= "ResetSleepTimer("
"sys_call("                		= "SysCall("
"sys_get_start_tick("        	= "SysGetStartTick("
"sys_keep_alive("           	= "SysKeepAlive("
"sys_io_map_read("           	= "SysIOMapRead("
"sys_io_map_write("          	= "SysIOMapWrite("
"sys_io_map_read_by_id("       	= "SysIOMapReadByID("
"sys_io_map_write_by_id("      	= "SysIOMapWriteByID("
"sys_datalog_write("        	= "SysDatalogWrite("
"sys_datalog_get_times("     	= "SysDatalogGetTimes("
"sys_read_sem_data("         	= "SysReadSemData("
"sys_write_sem_data("        	= "SysWriteSemData("
"sys_update_calib_cache_info("	= "SysUpdateCalibCacheInfo("
"sys_compute_calib_value("   	= "SysComputeCalibValue("
"get_memory_info("          	= "GetMemoryInfo("
"sys_memory_manager("       	= "SysMemoryManager("
"get_last_response_info("    	= "GetLastResponseInfo("
"sys_read_last_response("    	= "SysReadLastResponse("
"sleep_ms("               		= "Wait("					# sleep
"sleep("						= "Wait(1000*"              # functions
"yield("                  		= "Yield("
"stop_all_tasks("           	= "StopAllTasks("
"stop_program("           		= "Stop("
"exit_to("                 		= "ExitTo("
"precedes("               		= "Precedes("
"follows("                		= "Follows("
"acquire("                		= "Acquire("
"release("                		= "Release("
"start_task("              		= "StartTask("
"stop_task("               		= "StopTask("
"branch_test("             		= "BranchTest("
"branch_comp("             		= "BranchComp("
"set_io_map_bytes("          	= "SetIOMapBytes("
"set_io_map_value("          	= "SetIOMapValue("
"get_io_map_bytes("          	= "GetIOMapBytes("
"get_io_map_value("          	= "GetIOMapValue("
"get_low_speed_module_bytes(" 	= "GetLowSpeedModuleBytes("
"get_display_module_bytes("  	= "GetDisplayModuleBytes("
"get_comm_module_bytes("     	= "GetCommModuleBytes("
"get_command_module_bytes("  	= "GetCommandModuleBytes("
"set_command_module_bytes("  	= "SetCommandModuleBytes("
"set_low_speed_module_bytes(" 	= "SetLowSpeedModuleBytes("
"set_display_module_bytes("  	= "SetDisplayModuleBytes("
"set_comm_module_bytes("     	= "SetCommModuleBytes("
"set_sound_module_bytes("    	= "SetSoundModuleBytes("
"set_io_map_bytes_by_id("      	= "SetIOMapBytesByID("
"set_io_map_value_by_id("      	= "SetIOMapValueByID("
"get_io_map_bytes_by_id("      	= "GetIOMapBytesByID("
"get_io_map_value_by_id("      	= "GetIOMapValueByID("
"set_command_module_value("  	= "SetCommandModuleValue("
"set_io_ctrl_module_value("   	= "SetIOCtrlModuleValue("
"set_loader_module_value("   	= "SetLoaderModuleValue("
"set_ui_module_value("       	= "SetUIModuleValue("
"set_sound_module_value("    	= "SetSoundModuleValue("
"set_button_module_value("   	= "SetButtonModuleValue("
"set_input_module_value("    	= "SetInputModuleValue("
"set_output_module_value("   	= "SetOutputModuleValue("
"set_low_speed_module_value(" 	= "SetLowSpeedModuleValue("
"set_display_module_value("  	= "SetDisplayModuleValue("
"set_comm_module_value("     	= "SetCommModuleValue("
"get_command_module_value("  	= "GetCommandModuleValue("
"get_loader_module_value("   	= "GetLoaderModuleValue("
"get_sound_module_value("    	= "GetSoundModuleValue("
"get_button_module_value("   	= "GetButtonModuleValue("
"get_ui_module_value("       	= "GetUIModuleValue("
"get_input_module_value("    	= "GetInputModuleValue("
"get_output_module_value("   	= "GetOutputModuleValue("
"get_low_speed_module_value(" 	= "GetLowSpeedModuleValue("
"get_display_module_value("  	= "GetDisplayModuleValue("
"get_comm_module_value("     	= "GetCommModuleValue("

