# NXC Input

# Constants for use with the color calibration functions. 
"cal_point_0" 	= "INPUT_CAL_POINT_0"    
"cal_point_1" 	= "INPUT_CAL_POINT_1"    
"cal_point_2" 	= "INPUT_CAL_POINT_2"    
"no_of_points"	= "INPUT_NO_OF_POINTS"   

# Constants for use with the color calibration state function. 
"sensorcal" 	= "INPUT_SENSORCAL" 
"sensoroff" 	= "INPUT_SENSOROFF" 
"runningcal"	= "INPUT_RUNNINGCAL"
"startcal"  	= "INPUT_STARTCAL"  
"resetcal"  	= "INPUT_RESETCAL"  

# Constants for use with color sensor value arrays to index RGB and blank return values. 
"red"         	= "INPUT_RED"         
"green"       	= "INPUT_GREEN"       
"blue"        	= "INPUT_BLUE"        
"blank"       	= "INPUT_BLANK"       
"no_of_colors"	= "INPUT_NO_OF_COLORS"

# Constants for use with the ColorValue returned by the color sensor in full color mode. 
"blackcolor" 		= "INPUT_BLACKCOLOR" 
"bluecolor"  		= "INPUT_BLUECOLOR"  
"greencolor" 		= "INPUT_GREENCOLOR" 
"yellowcolor"		= "INPUT_YELLOWCOLOR"
"redcolor"   		= "INPUT_REDCOLOR"   
"whitecolor" 		= "INPUT_WHITECOLOR" 

# Constants for use with the Input module's Pin function. 
"pincmd_dir"   	= "INPUT_PINCMD_DIR"   
"pincmd_set"   	= "INPUT_PINCMD_SET"   
"pincmd_clear" 	= "INPUT_PINCMD_CLEAR" 
"pincmd_read"  	= "INPUT_PINCMD_READ"  
"pincmd_mask"  	= "INPUT_PINCMD_MASK"  
"pincmd_wait"  	= "INPUT_PINCMD_WAIT"  
"pindir_output"	= "INPUT_PINDIR_OUTPUT"
"pindir_input" 	= "INPUT_PINDIR_INPUT"

# Constants for use with set_input                                                      
"type_field"           	= "TypeField"           
"input_mode_field"      	= "InputModeField"      
"raw_value_field"       	= "RawValueField"       
"normalized_value_field"	= "NormalizedValueField"
"scaled_value_field"    	= "ScaledValueField"    
"invalid_data_field"    	= "InvalidDataField"    

# Constant offsets into the Input module IOMAP structure. 
"offset_custom_zero_offset"     	= "InputOffsetCustomZeroOffset"                                                      
"offset_ad_raw"                	= "InputOffsetADRaw"                                                      
"offset_sensor_raw"            	= "InputOffsetSensorRaw"                                                      
"offset_sensor_value"          	= "InputOffsetSensorValue"                                                      
"offset_sensor_type"           	= "InputOffsetSensorType"                                                      
"offset_sensor_mode"           	= "InputOffsetSensorMode"                                                      
"offset_sensor_boolean"        	= "InputOffsetSensorBoolean"                                                      
"offset_digi_pins_dir"          	= "InputOffsetDigiPinsDir"                                                      
"offset_digi_pins_in"           	= "InputOffsetDigiPinsIn"                                                      
"offset_digi_pins_out"          	= "InputOffsetDigiPinsOut"                                                      
"offset_custom_pct_full_scale"   	= "InputOffsetCustomPctFullScale"                                                      
"offset_custom_active_status"   	= "InputOffsetCustomActiveStatus"                                                      
"offset_invalid_data"          	= "InputOffsetInvalidData"                                                      
"offset_color_calibration"     	= "InputOffsetColorCalibration"                                                      
"offset_color_cal_limits"       	= "InputOffsetColorCalLimits"                                                      
"offset_color_ad_raw"           	= "InputOffsetColorADRaw"                                                      
"offset_color_sensor_raw"       	= "InputOffsetColorSensorRaw"                                                      
"offset_color_sensor_value"     	= "InputOffsetColorSensorValue"                                                      
"offset_color_boolean"         	= "InputOffsetColorBoolean"                                                      
"offset_color_calibration_state"	= "InputOffsetColorCalibrationState"      

# Input port constants are used when calling NXC sensor control API functions. 
"s1"	= "S1"
"s2"	= "S2"
"s3"	= "S3"
"s4"	= "S4"

# Constants for use when directly controlling or reading a port's digital pin state. 
"digi0"	= "INPUT_DIGI0"
"digi1"	= "INPUT_DIGI1"

# Input port constants are used when calling sensor control API functions.
# These constants are intended for use in NBC. 
"in_1"	= "IN_1"
"in_2"	= "IN_2"
"in_3"	= "IN_3"
"in_4"	= "IN_4"

# Use the combined sensor type and mode constants to configure both the sensor mode and type in a single function call. 
"touch"         = "_SENSOR_CFG"                                                         
"light"         = "_SENSOR_CFG"                                                         
"rotation"      = "_SENSOR_CFG"                                                         
"celsius"       = "_SENSOR_CFG"                                                         
"fahrenheit"    = "_SENSOR_CFG"                                                         
"pulse"         = "_SENSOR_CFG"                                                         
"edge"          = "_SENSOR_CFG"                                                         
"nxtlight"      = "_SENSOR_CFG"                                                         
"sound"         = "_SENSOR_CFG"                                                         
"lowspeed_9v"   = "_SENSOR_CFG"                                                         
"lowspeed"      = "_SENSOR_CFG"                                                         
"colorfull"     = "_SENSOR_CFG"                                                         
"colorred"      = "_SENSOR_CFG"                                                         
"colorgreen"    = "_SENSOR_CFG"                                                         
"colorblue"     = "_SENSOR_CFG"                                                         
"colornone"     = "_SENSOR_CFG"                                                         

# Use sensor mode constants to configure an input port for the desired sensor mode.
# The constants are intended for use in NBC. 
"mode_raw"          	= "IN_MODE_RAW"          
"mode_boolean"      	= "IN_MODE_BOOLEAN"      
"mode_transitioncnt"	= "IN_MODE_TRANSITIONCNT"
"mode_periodcounter"	= "IN_MODE_PERIODCOUNTER"
"mode_pctfullscale" 	= "IN_MODE_PCTFULLSCALE" 
"mode_celsius"      	= "IN_MODE_CELSIUS"      
"mode_fahrenheit"   	= "IN_MODE_FAHRENHEIT"   
"mode_anglestep"    	= "IN_MODE_ANGLESTEP"    
"mode_slopemask"    	= "IN_MODE_SLOPEMASK"    
"mode_modemask"     	= "IN_MODE_MODEMASK"     

# Use sensor type constants to configure an input port for a specific type of sensor.
# These constants are intended for use in NBC. 
"type_no_sensor"     	= "IN_TYPE_NO_SENSOR"     
"type_switch"        	= "IN_TYPE_SWITCH"        
"type_temperature"   	= "IN_TYPE_TEMPERATURE"   
"type_reflection"    	= "IN_TYPE_REFLECTION"    
"type_angle"         	= "IN_TYPE_ANGLE"         
"type_light_active"  	= "IN_TYPE_LIGHT_ACTIVE"  
"type_light_inactive"	= "IN_TYPE_LIGHT_INACTIVE"
"type_sound_db"      	= "IN_TYPE_SOUND_DB"      
"type_sound_dba"     	= "IN_TYPE_SOUND_DBA"     
"type_custom"        	= "IN_TYPE_CUSTOM"        
"type_lowspeed"      	= "IN_TYPE_LOWSPEED"      
"type_lowspeed_9v"   	= "IN_TYPE_LOWSPEED_9V"   
"type_hispeed"       	= "IN_TYPE_HISPEED"       
"type_colorfull"     	= "IN_TYPE_COLORFULL"     
"type_colorred"      	= "IN_TYPE_COLORRED"      
"type_colorgreen"    	= "IN_TYPE_COLORGREEN"    
"type_colorblue"     	= "IN_TYPE_COLORBLUE"     
"type_colornone"     	= "IN_TYPE_COLORNONE"     
"type_colorexit"     	= "IN_TYPE_COLOREXIT"    

# Use sensor mode constants to configure an input port for the desired sensor mode.  
"mode_raw"          = "IN_MODE_RAW"
"mode_bool"         = "IN_MODE_BOOLEAN"
"mode_edge"         = "IN_MODE_TRANSITIONCNT"
"mode_pulse"        = "IN_MODE_PERIODCOUNTER"
"mode_percent"      = "IN_MODE_PCTFULLSCALE"
"mode_celsius"      = "IN_MODE_CELSIUS"
"mode_fahrenheit"   = "IN_MODE_FAHRENHEIT"
"mode_rotation"     = "IN_MODE_ANGLESTEP"

# Use sensor type constants to configure an input port for a specific type of sensor. 
"type_none"          	= "IN_TYPE_NO_SENSOR"
"type_touch"         	= "IN_TYPE_SWITCH"
"type_temperature"   	= "IN_TYPE_TEMPERATURE"
"type_light"         	= "IN_TYPE_REFLECTION"
"type_rotation"      	= "IN_TYPE_ANGLE"
"type_light_active"  	= "IN_TYPE_LIGHT_ACTIVE"
"type_light_inactive"	= "IN_TYPE_LIGHT_INACTIVE"
"type_sound_db"      	= "IN_TYPE_SOUND_DB"
"type_sound_dba"     	= "IN_TYPE_SOUND_DBA"
"type_custom"        	= "IN_TYPE_CUSTOM"
"type_lowspeed"      	= "IN_TYPE_LOWSPEED"
"type_lowspeed_9v"   	= "IN_TYPE_LOWSPEED_9V"
"type_highspeed"     	= "IN_TYPE_HISPEED"
"type_colorfull"     	= "IN_TYPE_COLORFULL"
"type_colorred"      	= "IN_TYPE_COLORRED"
"type_colorgreen"    	= "IN_TYPE_COLORGREEN"
"type_colorblue"     	= "IN_TYPE_COLORBLUE"
"type_colornone"     	= "IN_TYPE_COLORNONE"

# 
"custominactive"	= "INPUT_CUSTOMINACTIVE"
"custom9v"      	= "INPUT_CUSTOM9V"      
"customactive"  	= "INPUT_CUSTOMACTIVE"  
"invalid_data"  	= "INPUT_INVALID_DATA"  

# Functions for accessing and modifying input module features.
"sensor__set_type("                		    = "SetSensorType("                                                          
"sensor__set_mode("          				= "SetSensorMode("                                                          
"sensor__clear("            				= "ClearSensor("                                                          
"sensor__reset("            				= "ResetSensor("                                                          
"sensor__set("              				= "SetSensor("                                                          
"sensor__set_touch("         				= "SetSensorTouch("                                                          
"sensor__set_light("         				= "SetSensorLight("                                                          
"sensor__set_sound("         				= "SetSensorSound("                                                          
"sensor__set_lowspeed("      				= "SetSensorLowspeed("                                                          
"sensor__set_ultrasonic("    				= "SetSensorUltrasonic("                                                          
"sensor__set_e_meter("        				= "SetSensorEMeter("                                                          
"sensor__set_temperature("   				= "SetSensorTemperature("                                                          
"sensor__set_color_full("     				= "SetSensorColorFull("                                                          
"sensor__set_color_red("      				= "SetSensorColorRed("                                                          
"sensor__set_color_green("    				= "SetSensorColorGreen("                                                          
"sensor__set_color_blue("     				= "SetSensorColorBlue("                                                          
"sensor__set_color_none("     				= "SetSensorColorNone("                                                          
"get_input("                   			    = "GetInput("                                                          
"set_input("                   			    = "SetInput("                                                          
"sensorx("                      			= "Sensor("                                                          
"sensor__boolean("            				= "SensorBoolean("                                                          
"sensor__digi_pins_direction("        		= "SensorDigiPinsDirection("                                                          
"sensor__digi_pins_output_level("      	    = "SensorDigiPinsOutputLevel("                                                          
"sensor__digi_pins_status("           		= "SensorDigiPinsStatus("                                                          
"sensor__invalid("                  		= "SensorInvalid("                                                          
"sensor__mode("                     		= "SensorMode("                                                          
"sensor__normalized("               		= "SensorNormalized("                                                          
"sensor__raw("                      		= "SensorRaw("                                                          
"sensor__scaled("                   		= "SensorScaled("                                                          
"sensor__type("                     		= "SensorType("                                                          
"sensor__value("                    		= "SensorValue("                                                          
"sensor__value_bool("                		= "SensorValueBool("                                                          
"sensor__value_raw("                 		= "SensorValueRaw("                                                          
"sensor__custom_active_status("       		= "CustomSensorActiveStatus("                                                          
"sensor__custom_percent_full_scale("   	    = "CustomSensorPercentFullScale("                                                          
"sensor__custom_zero_offset("         		= "CustomSensorZeroOffset("                                                          
"sensor__set_custom_active_status("    	    = "SetCustomSensorActiveStatus("                                                          
"sensor__set_custom_percent_full_scale("	= "SetCustomSensorPercentFullScale("                                                          
"sensor__set_custom_zero_offset("      	    = "SetCustomSensorZeroOffset("                                                          
"sensor__set_boolean("               		= "SetSensorBoolean("                                                          
"sensor__set_digi_pins_direction("     	    = "SetSensorDigiPinsDirection("                                                          
"sensor__set_digi_pins_output_level("   	= "SetSensorDigiPinsOutputLevel("                                                          
"sensor__set_digi_pins_status("         	= "SetSensorDigiPinsStatus("                                                          
"sensor__sys_color_read("             		= "SysColorSensorRead("                                                          
"sensor__read_color_ex("              		= "ReadSensorColorEx("                                                          
"sensor__read_color_raw("             		= "ReadSensorColorRaw("                                                          
"color_ad_raw("                    		    = "ColorADRaw("                                                          
"color_boolean("                   		    = "ColorBoolean("                                                          
"color_calibration("               		    = "ColorCalibration("                                                          
"color_calibration_state("         		    = "ColorCalibrationState("                                                          
"color_cal_limits("                		    = "ColorCalLimits("                                                          
"color_raw("                 				= "ColorSensorRaw("                                                          
"color_value("               				= "ColorSensorValue("                                                          
"sys_input_pin_function("          		    = "SysInputPinFunction("                                                          